version: '3.4'

volumes:
  mongo-data:

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    env_file:
      - mongo.env
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
